import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { InteropEngine } from "../interop-engine/interop-engine.mjs";

/**
 * Data migrations that run after an upgrade.
 *
 * Managed engine files are replaced wholesale; owner data never is. When a new
 * version changes the shape of that data, the change belongs here: a named,
 * idempotent step that runs once, is recorded in `.astack/upgrade-state.json`
 * and is safe to re-run.
 */
export const migrations = [
  {
    id: "2026.1-structured-memory",
    description: "Create the multi-faceted memory store beside the markdown scopes.",
    appliesTo: (root) => !existsSync(join(root, ".astack", "memory")),
    run: (root) => {
      mkdirSync(join(root, ".astack", "memory"), { recursive: true });
      return "created .astack/memory for the structured facets";
    }
  },
  {
    id: "2026.2-owner-profile",
    description: "Seed the owner profile from the existing configuration.",
    appliesTo: (root) => !existsSync(join(root, ".astack", "owner", "profile.json")),
    run: (root) => {
      const configPath = join(root, "astack.config.yaml");
      const conversation = existsSync(configPath)
        ? /\n\s*conversation:\s*(\w+)/.exec(readFileSync(configPath, "utf8"))?.[1] ?? "fa"
        : "fa";
      mkdirSync(join(root, ".astack", "owner"), { recursive: true });
      writeFileSync(
        join(root, ".astack", "owner", "profile.json"),
        JSON.stringify(
          {
            name: null,
            languages: { conversation, assets: "en" },
            responseStyle: "concise",
            companies: [],
            activeProjects: [],
            recurringWorkflows: [],
            preferences: [],
            doNotStore: ["passwords", "otp", "card numbers", "national id numbers"],
            updatedAt: new Date().toISOString()
          },
          null,
          2
        ) + "\n",
        "utf8"
      );
      return "seeded the owner identity capsule";
    }
  },
  {
    id: "2026.3-authority-defaults",
    description: "Install the default authority policy so external actions are gated from the first run.",
    appliesTo: (root) => !existsSync(join(root, ".astack", "security", "authority.json")),
    run: (root) => {
      mkdirSync(join(root, ".astack", "security"), { recursive: true });
      writeFileSync(
        join(root, ".astack", "security", "authority.json"),
        JSON.stringify(
          { defaultLevel: "L2", autonomous: ["L0", "L1", "L2"], requireApproval: ["L4"], domains: {}, tools: {}, sites: {} },
          null,
          2
        ) + "\n",
        "utf8"
      );
      return "installed the default authority policy (L2, approval required for L4)";
    }
  },
  {
    id: "2026.4-learned-skills-directory",
    description: "Create the learned skills directory so forged skills survive later upgrades.",
    appliesTo: (root) => !existsSync(join(root, "skills", "learned")),
    run: (root) => {
      mkdirSync(join(root, "skills", "learned"), { recursive: true });
      writeFileSync(
        join(root, "skills", "learned", "README.md"),
        [
          "# Learned Skills",
          "",
          "Skills in this directory are generated by the learning engine from repeated real work.",
          "They are preserved across upgrades and never overwritten by the AStack core.",
          "",
          "- inspect: `astack skill list --source learned`",
          "- validate: `astack skill test <id>`",
          "- promote: `astack skill promote <id> --status active`",
          "- roll back: `astack skill rollback <id> <version>`",
          ""
        ].join("\n"),
        "utf8"
      );
      return "created skills/learned";
    }
  },
  {
    id: "2026.5-legacy-memory-import",
    description: "Import owner decisions from the markdown memory into the structured decision facet.",
    appliesTo: (root) => existsSync(join(root, "memory", "decision.md")) && !existsSync(join(root, ".astack", "memory", "decision.jsonl")),
    run: (root) => {
      const text = readFileSync(join(root, "memory", "decision.md"), "utf8");
      const entries = [...text.matchAll(/^-\s+(.{4,300})$/gm)].map((match) => match[1].trim());
      if (!entries.length) {
        return "no decisions to import";
      }
      mkdirSync(join(root, ".astack", "memory"), { recursive: true });
      const now = new Date().toISOString();
      const lines = entries.map((entry, index) =>
        JSON.stringify({
          id: "dec-import-" + index,
          facet: "decision",
          type: "decision",
          at: now,
          updatedAt: now,
          scope: "decision",
          domain: null,
          project: null,
          title: entry.slice(0, 140),
          body: entry,
          tags: ["imported"],
          refs: [],
          entities: [],
          validFrom: now,
          validTo: null,
          supersedes: null,
          supersededBy: null,
          importance: 0.7,
          weight: 1.3,
          confidence: 0.6,
          hits: 0,
          lastHit: null,
          source: "migration:2026.5",
          expiresAt: null,
          digest: "import-" + index,
          meta: {}
        })
      );
      writeFileSync(join(root, ".astack", "memory", "decision.jsonl"), lines.join("\n") + "\n", "utf8");
      return "imported " + entries.length + " decisions into the structured memory";
    }
  },
  {
    id: "2026.6-ignore-runtime-state",
    description: "Teach an existing .gitignore about the directories the new engines write.",
    appliesTo: (root) =>
      existsSync(join(root, ".gitignore")) && !readFileSync(join(root, ".gitignore"), "utf8").includes(".astack/browser/"),
    run: (root) => {
      // Sessions, credentials and evidence live under .astack. An install that
      // upgraded from 2.0 keeps its own .gitignore, so the new rules have to be
      // appended rather than shipped.
      const path = join(root, ".gitignore");
      const current = readFileSync(path, "utf8");
      const rules = [
        ".astack/context/",
        ".astack/graph/",
        ".astack/learning/",
        ".astack/memory/",
        ".astack/missions/",
        ".astack/scheduler/",
        ".astack/signals/",
        ".astack/browser/",
        ".astack/evidence/",
        ".astack/audit/",
        ".astack/approvals/",
        ".astack/security/",
        ".astack/owner/",
        ".astack/runtimes/",
        ".astack/tools/"
      ].filter((rule) => !current.includes(rule));
      if (!rules.length) {
        return "nothing to add";
      }
      writeFileSync(path, current.replace(/\s*$/, "\n") + rules.join("\n") + "\n", "utf8");
      return "added " + rules.length + " ignore rules for runtime state";
    }
  },
  {
    id: "2026.7-runtime-interop",
    description: "Wire Claude Code and Codex to the shared AGENTS.md contract, the astack MCP server, the session hooks and the journal.",
    appliesTo: (root) =>
      (existsSync(join(root, "AGENTS.md")) || existsSync(join(root, "system", "agent-contract.md"))) && new InteropEngine(root).plan().some((entry) => entry.action !== "ok"),
    run: (root) => {
      // CLAUDE.md, .mcp.json and the runtime settings belong to the owner, so the
      // wiring is merged into them rather than shipped over them.
      const changed = new InteropEngine(root).sync().filter((entry) => entry.action !== "ok");
      const ignore = join(root, ".gitignore");
      if (existsSync(ignore)) {
        // The journal and the Graphify output are machine-local and rebuilt on demand.
        const current = readFileSync(ignore, "utf8");
        const rules = [".astack/interop/", "graphify-out/"].filter((rule) => !current.includes(rule));
        if (rules.length) {
          writeFileSync(ignore, current.replace(/\s*$/, "\n") + rules.join("\n") + "\n", "utf8");
        }
      }
      return changed.length ? "wired " + changed.map((entry) => entry.path).join(", ") : "runtime wiring already in place";
    }
  }
];

export function statePath(root) {
  return join(root, ".astack", "upgrade-state.json");
}

export function readState(root) {
  const path = statePath(root);
  if (!existsSync(path)) {
    return { applied: [], history: [] };
  }
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return { applied: [], history: [] };
  }
}

export function writeState(root, state) {
  mkdirSync(join(root, ".astack"), { recursive: true });
  writeFileSync(statePath(root), JSON.stringify(state, null, 2) + "\n", "utf8");
  return state;
}

export function pendingMigrations(root) {
  const state = readState(root);
  return migrations.filter((migration) => !state.applied.includes(migration.id) && migration.appliesTo(root));
}

/**
 * Apply every pending migration. Failures are recorded but never abort the
 * upgrade: engine code is already in place and the owner is told what to fix.
 */
export function runMigrations(root, { dryRun = false } = {}) {
  const state = readState(root);
  const results = [];
  for (const migration of migrations) {
    if (state.applied.includes(migration.id)) {
      continue;
    }
    if (!migration.appliesTo(root)) {
      // Not applicable now does not mean finished: appliesTo is the idempotency
      // guard, so leave it free to run when the condition appears.
      results.push({ id: migration.id, status: "skipped", detail: "not applicable" });
      continue;
    }
    if (dryRun) {
      results.push({ id: migration.id, status: "pending", detail: migration.description });
      continue;
    }
    try {
      const detail = migration.run(root);
      state.applied.push(migration.id);
      results.push({ id: migration.id, status: "applied", detail });
    } catch (error) {
      // A failure is not recorded as applied, so the next run tries again.
      results.push({ id: migration.id, status: "failed", detail: error.message });
    }
  }
  if (!dryRun) {
    state.history = [...(state.history ?? []), { at: new Date().toISOString(), results }].slice(-20);
    writeState(root, state);
  }
  return results;
}
